version: "3.10"

services:
    app:
        container_name: ${CONTAINER_NAME}-app
        build:
            dockerfile: docker/Dockerfile
            context: .
        image: ${CONTAINER_NAME}/${CONTAINER_NAME}-app-image
        volumes:
            - ./app:/src
            - ~/.cache/pip-docker/:/root/.cache/pip
        depends_on:
            - db
        ports:
            - "8000:8000"
        env_file:
            - .env
        networks:
            - private
            - traefik_webgateway
        environment:
            - DEBUG=true
            - WATCHFILES_FORCE_POLLING=true
        labels:
            - traefik.enable=true
            - traefik.http.services.${CONTAINER_NAME}-app.loadbalancer.server.port=8000
            - traefik.http.routers.${CONTAINER_NAME}-app.rule=Host(`${API_HOST}`)
            - traefik.http.routers.${CONTAINER_NAME}-app.entrypoints=web
            # https
            - traefik.http.middlewares.${CONTAINER_NAME}-app-redirect-websecure.redirectscheme.scheme=https
            - traefik.http.routers.${CONTAINER_NAME}-app.middlewares=${CONTAINER_NAME}-app-redirect-websecure
            - traefik.http.routers.${CONTAINER_NAME}-app-websecure.rule=Host(`${API_HOST}`)
            - traefik.http.routers.${CONTAINER_NAME}-app-websecure.tls=true
            - traefik.http.routers.${CONTAINER_NAME}-app-websecure.entrypoints=websecure
            # WEBSOCKET
            # HTTP
            - traefik.http.routers.${CONTAINER_NAME}-ws.rule=Host(`${WS_HOST}`)
            - traefik.http.routers.${CONTAINER_NAME}-ws.entrypoints=web
            # HTTPS
            - traefik.http.middlewares.${CONTAINER_NAME}-ws-redirect-websecure.redirectscheme.scheme=https
            - traefik.http.routers.${CONTAINER_NAME}-ws.middlewares=${CONTAINER_NAME}-ws-redirect-websecure
            - traefik.http.routers.${CONTAINER_NAME}-ws-websecure.rule=Host(`${WS_HOST}`)
            - traefik.http.routers.${CONTAINER_NAME}-ws-websecure.tls=true
            - traefik.http.routers.${CONTAINER_NAME}-ws-websecure.tls.certresolver=letsencrypt
            - traefik.http.routers.${CONTAINER_NAME}-ws-websecure.entrypoints=websecure

    frontend:
        container_name: ${CONTAINER_NAME}-frontend
        build:
            dockerfile: ./docker/Frontend.Dockerfile
            context: ./
        image: ${CONTAINER_NAME}/${CONTAINER_NAME}-frontend-image
        depends_on:
            - app
        labels:
            - traefik.enable=true
            - traefik.http.routers.${CONTAINER_NAME}-front.rule=Host(`${HOST}`)
            - traefik.http.routers.${CONTAINER_NAME}-front.entrypoints=web
            # https is optional, delete next lines when you don't need this
            - traefik.http.middlewares.${CONTAINER_NAME}-front-redirect-websecure.redirectscheme.scheme=https
            - traefik.http.routers.${CONTAINER_NAME}-front.middlewares=${CONTAINER_NAME}-front-redirect-websecure
            - traefik.http.routers.${CONTAINER_NAME}-front-websecure.rule=Host(`${HOST}`)
            - traefik.http.routers.${CONTAINER_NAME}-front-websecure.tls=true
            - traefik.http.routers.${CONTAINER_NAME}-front-websecure.entrypoints=websecure
        networks:
            - private
            - traefik_webgateway
        volumes:
            - ./frontend/dist:/usr/share/nginx/html
        cap_add:
            - SYS_PTRACE
        privileged: true

    db:
        container_name: ${CONTAINER_NAME}-db
        image: postgres:15.4
        volumes:
            - hypothesis_postgres:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${DB_USER}" ]
            timeout: 45s
            interval: 10s
            retries: 10
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            - private

    redis:
        image: redis
        volumes:
            - redis:/data
        networks:
            - private
        command:
            - 'redis-server'

    celery_worker:
        build:
          dockerfile: docker/Dockerfile
          context: .
        image:  ${CONTAINER_NAME}/${CONTAINER_NAME}-celery-worker
        command: /start-celeryworker
        volumes:
          - .:/src
        networks:
            - private
        env_file:
          - .env
        depends_on:
          - redis
          - db

    celery_beat:
        build:
          dockerfile: docker/Dockerfile
          context: .
        image:  ${CONTAINER_NAME}/${CONTAINER_NAME}-celery-beat
        command: /start-celerybeat
        volumes:
          - .:/src
        networks:
            - private
        env_file:
          - .env
        depends_on:
          - redis
          - db

    flower:
        build:
          dockerfile: docker/Dockerfile
          context: .
        image:  ${CONTAINER_NAME}/${CONTAINER_NAME}-celery-flower
        command: /start-flower
        volumes:
          - .:/src
        networks:
            - private
        env_file:
          - .env
        ports:
          - "5557:5555"
        depends_on:
          - redis
          - db

networks:
    traefik_webgateway:
        external: true
    private:
        name: ${CONTAINER_NAME}-private
        driver: bridge

volumes:
    redis:
    hypothesis_postgres:
        external: true
