"""add_domain_to_organizations

Revision ID: bf8703250d80
Revises: 5041ebd15510
Create Date: 2023-09-27 11:06:44.516236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf8703250d80"
down_revision = "5041ebd15510"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organization", sa.Column("domain", sa.String(), nullable=True))
    op.alter_column("room", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("room", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("organization", "domain")
    # ### end Alembic commands ###
