"""add_content_html_to_template

Revision ID: 75f7571f3d41
Revises: d7495586190f
Create Date: 2023-10-23 13:29:39.272145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75f7571f3d41"
down_revision = "d7495586190f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("template", sa.Column("content_html", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("template", "content_html")
    # ### end Alembic commands ###
