"""add_visibility_to_room

Revision ID: ae59744a0a2e
Revises: f9ff4b9d6477
Create Date: 2023-09-08 13:34:37.056939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae59744a0a2e"
down_revision = "f9ff4b9d6477"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room",
        sa.Column(
            "visibility",
            sa.Enum("just_me", "organization", name="visibility_enum"),
            server_default="just_me",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room", "visibility")
    # ### end Alembic commands ###
