"""add_picture_to_messages

Revision ID: e76528955fe5
Revises: 5c82e722d66c
Create Date: 2023-09-25 15:14:13.624786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e76528955fe5"
down_revision = "5c82e722d66c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("user_picture", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "user_picture")
    # ### end Alembic commands ###
