"""add_templates

Revision ID: 5c82e722d66c
Revises: 7c067781d750
Create Date: 2023-09-21 14:43:32.168989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5c82e722d66c"
down_revision = "7c067781d750"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template",
        sa.Column("uuid", postgresql.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("share", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("just_me", "organization", name="template_visibility_choices"),
            server_default="just_me",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
            name=op.f("template_user_id_fkey"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("template_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("template")
    sa.Enum("just_me", "organization", name="template_visibility_choices").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
