"""add_user_to_message_and_user_info

Revision ID: c7cfc0dbb74d
Revises: ae59744a0a2e
Create Date: 2023-09-14 13:39:35.285640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7cfc0dbb74d"
down_revision = "ae59744a0a2e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_user", sa.Column("picture", sa.String(), nullable=True))
    op.add_column("auth_user", sa.Column("name", sa.String(), nullable=True))
    op.add_column("message", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("message_user_id_fkey"),
        "message",
        "auth_user",
        ["user_id"],
        ["id"],
        ondelete="NO ACTION",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("message_user_id_fkey"), "message", type_="foreignkey")
    op.drop_column("message", "user_id")
    op.drop_column("auth_user", "name")
    op.drop_column("auth_user", "picture")
    # ### end Alembic commands ###
