"""add_content_html_field_to_message_table

Revision ID: 6374c52b5b50
Revises: 75f7571f3d41
Create Date: 2023-10-31 14:45:48.459221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6374c52b5b50"
down_revision = "75f7571f3d41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("content_html", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "content_html")
    # ### end Alembic commands ###
