"""change_on_delete

Revision ID: e45346cb129a
Revises: 91c287399baf
Create Date: 2023-09-01 11:04:56.797316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e45346cb129a"
down_revision = "91c287399baf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("message_room_id_fkey", "message", type_="foreignkey")
    op.create_foreign_key(
        op.f("message_room_id_fkey"),
        "message",
        "room",
        ["room_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("message_room_id_fkey"), "message", type_="foreignkey")
    op.create_foreign_key(
        "message_room_id_fkey", "message", "room", ["room_id"], ["uuid"]
    )
    # ### end Alembic commands ###
