"""add_share_to_room

Revision ID: 8eb08eb72113
Revises: e45346cb129a
Create Date: 2023-09-06 14:11:19.783736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8eb08eb72113"
down_revision = "e45346cb129a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room", sa.Column("share", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room", "share")
    # ### end Alembic commands ###
