"""add_update_at_info_to_tables

Revision ID: 744747b57afe
Revises: 6374c52b5b50
Create Date: 2023-11-06 13:17:40.582977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "744747b57afe"
down_revision = "6374c52b5b50"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "organization",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "updated_at")
    op.drop_column("message", "updated_at")
    # ### end Alembic commands ###
