"""add_update_at_to_room

Revision ID: a9fdc38a2283
Revises: e051bc1608f8
Create Date: 2023-10-06 13:45:24.510319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9fdc38a2283"
down_revision = "e051bc1608f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("room", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room", "updated_at")
    # ### end Alembic commands ###
