"""change_user_picture_name_in_message

Revision ID: 5041ebd15510
Revises: e76528955fe5
Create Date: 2023-09-26 12:10:34.235475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5041ebd15510"
down_revision = "e76528955fe5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("sender_picture", sa.String(), nullable=True))
    op.drop_column("message", "user_picture")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("user_picture", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("message", "sender_picture")
    # ### end Alembic commands ###
