"""chat_proxy

Revision ID: 2ca59d72ff53
Revises: 59f90d90646c
Create Date: 2023-08-24 08:40:27.615532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2ca59d72ff53"
down_revision = "59f90d90646c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("uuid", postgresql.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
            name=op.f("room_user_id_fkey"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("room_pkey")),
    )
    op.create_table(
        "message",
        sa.Column("uuid", postgresql.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("room_id", postgresql.UUID(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["room.uuid"],
            name=op.f("message_room_id_fkey"),
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("message_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    op.drop_table("room")
    # ### end Alembic commands ###
