"""db_to_classes_changes

Revision ID: d7495586190f
Revises: bf8703250d80
Create Date: 2023-10-09 12:28:08.464982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d7495586190f"
down_revision = "bf8703250d80"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization_admin",
        "organization_uuid",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    op.alter_column(
        "organization_admin", "auth_user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column(
        "organization_user",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.alter_column(
        "organization_user",
        "organization_uuid",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    op.alter_column(
        "organization_user", "auth_user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column("room", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.alter_column("room", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.add_column("template", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "template", sa.Column("organization_uuid", postgresql.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "template",
        "organization",
        ["organization_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "template", type_="foreignkey")
    op.drop_column("template", "organization_uuid")
    op.drop_column("template", "updated_at")
    op.alter_column("room", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("room", "updated_at")
    op.alter_column(
        "organization_user", "auth_user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "organization_user",
        "organization_uuid",
        existing_type=postgresql.UUID(),
        nullable=True,
    )
    op.drop_column("organization_user", "created_at")
    op.alter_column(
        "organization_admin", "auth_user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "organization_admin",
        "organization_uuid",
        existing_type=postgresql.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###
