"""token_usage_table

Revision ID: abf0b768178a
Revises: 744747b57afe
Create Date: 2023-12-11 00:57:29.358157

"""
from alembic import op
import sqlalchemy as sa

from src.db_types import AwareDateTime

# revision identifiers, used by Alembic.
revision = "abf0b768178a"
down_revision = "744747b57afe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_usage",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("message", sa.Column("token_usage_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "message", "token_usage", ["token_usage_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_column("message", "token_usage_id")
    op.drop_table("token_usage")
    # ### end Alembic commands ###
