"""tables_to_classes

Revision ID: e051bc1608f8
Revises: bf8703250d80
Create Date: 2023-10-05 15:56:15.225023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e051bc1608f8"
down_revision = "bf8703250d80"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization_admin",
        "organization_uuid",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    op.alter_column(
        "organization_admin", "auth_user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.add_column(
        "organization_user",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.alter_column(
        "organization_user",
        "organization_uuid",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    op.alter_column(
        "organization_user", "auth_user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("room", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("room", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "organization_user", "auth_user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "organization_user",
        "organization_uuid",
        existing_type=postgresql.UUID(),
        nullable=True,
    )
    op.drop_column("organization_user", "created_at")
    op.alter_column(
        "organization_admin", "auth_user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "organization_admin",
        "organization_uuid",
        existing_type=postgresql.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###
