"""nullable_true_user_model_default

Revision ID: 54df4994baaf
Revises: 98b7814258f3
Create Date: 2024-07-18 09:19:21.801487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54df4994baaf"
down_revision = "98b7814258f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_model", "defaultSelected", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_model", "defaultSelected", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
