"""add_content_dict_field_to_message_table

Revision ID: 2b2c419c394d
Revises: ffda8e871a8d
Create Date: 2024-03-21 12:09:01.929973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b2c419c394d"
down_revision = "ffda8e871a8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("content_dict", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "content_dict")
    # ### end Alembic commands ###
