"""add_org_model_table

Revision ID: 6c8b28a13c55
Revises: 54df4994baaf
Create Date: 2024-08-08 13:24:25.453219

"""
import sqlalchemy as sa
from alembic import op

from src.db_types import AwareDateTime

# revision identifiers, used by Alembic.
revision = "6c8b28a13c55"
down_revision = "54df4994baaf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_model",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("organization_uuid", sa.UUID(), nullable=False),
        sa.Column("user_model_uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_uuid"], ["organization.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_model_uuid"], ["user_model.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_model")
    # ### end Alembic commands ###
