"""change_user_model_field_model_to_defaultSelected

Revision ID: 98b7814258f3
Revises: 416bc30296f7
Create Date: 2024-07-18 09:16:20.616905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98b7814258f3"
down_revision = "416bc30296f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_model", sa.Column("defaultSelected", sa.String(), nullable=False)
    )
    op.drop_column("user_model", "model")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_model",
        sa.Column("model", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("user_model", "defaultSelected")
    # ### end Alembic commands ###
