"""add

Revision ID: 28ee8a1434e7
Revises: f7246f938610
Create Date: 2024-02-19 18:01:37.877785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "28ee8a1434e7"
down_revision = "f7246f938610"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_file", sa.Column("extension", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_file", "extension")
    # ### end Alembic commands ###
