"""change_active_to_default_name_in_user_model

Revision ID: 416bc30296f7
Revises: fe3cb90b8c6b
Create Date: 2024-07-18 08:40:16.031193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "416bc30296f7"
down_revision = "fe3cb90b8c6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_model",
        sa.Column("default", sa.Boolean(), server_default="false", nullable=False),
    )
    op.drop_column("user_model", "active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_model",
        sa.Column(
            "active",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user_model", "default")
    # ### end Alembic commands ###
