"""token_usage_add_sequence

Revision ID: eb38eaef1e40
Revises: 3500f4145a8d
Create Date: 2024-05-28 00:27:37.179004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.db_types import AwareDateTime

# revision identifiers, used by Alembic.
revision = "eb38eaef1e40"
down_revision = "3500f4145a8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE token_usage ALTER COLUMN id DROP IDENTITY")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "token_usage",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###

