"""add_elapsed_message_time

Revision ID: f7a1a7719961
Revises: abf0b768178a
Create Date: 2024-01-11 16:33:41.647920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7a1a7719961"
down_revision = "abf0b768178a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("elapsed_time", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "elapsed_time")
    # ### end Alembic commands ###
