"""add_server_room_default_update_at

Revision ID: ffda8e871a8d
Revises: 28ee8a1434e7
Create Date: 2024-02-21 12:28:28.264868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import update

from src.database import Room

# revision identifiers, used by Alembic.
revision = "ffda8e871a8d"
down_revision = "28ee8a1434e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # update all existing rooms update_at field with create_at value if update_at is null
    op.execute(
        update(Room).where(Room.updated_at.is_(None)).values(updated_at=Room.created_at)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
