"""add_active_users_table

Revision ID: 42180b403ff1
Revises: f7a1a7719961
Create Date: 2024-01-24 01:04:08.028796

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.db_types import AwareDateTime

# revision identifiers, used by Alembic.
revision = "42180b403ff1"
down_revision = "f7a1a7719961"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_room_user",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("room_uuid", postgresql.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["room_uuid"], ["room.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["auth_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_uuid", "user_id", name="uq_active_room_user"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("active_room_user")
    # ### end Alembic commands ###
