"""add_file_to_database

Revision ID: d44bd42784cd
Revises: f7a1a7719961
Create Date: 2024-01-18 12:10:56.034251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src.db_types import AwareDateTime

# revision identifiers, used by Alembic.
revision = "d44bd42784cd"
down_revision = "f7a1a7719961"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("uuid", postgresql.UUID(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user"], ["auth_user.id"], ondelete="NO ACTION"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file")
    # ### end Alembic commands ###
