name: Run formats and linters

on:
  pull_request:
    branches:
      - '**'

jobs:
  run_formats:
    name: Run formats
    runs-on: ubuntu-latest
    container: python:3.10.7
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r ./app/requirements/dev.txt
        continue-on-error: true

      - name: Format with autoflake
        run: |
          autoflake --config ./app/formatting_config.cfg --recursive ./app/src

      - name: Format with black
        run: |
          black ./app/src --config ./app/formatting_config.cfg

      - name: Format with isort
        run: |
          isort ./app/src --profile black

  run_linters:
    name: Run linters
    runs-on: ubuntu-latest
    container: python:3.10.7
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r ./app/requirements/dev.txt
        continue-on-error: true

      - name: Lint with flake8
        run: |
          flake8 ./app/src --config ./app/linting_config.cfg

      - name: Lint with mypy
        run: |
          mypy ./app/src --config-file ./app/linting_config.cfg
