name: PostgreSQL service example
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:3.10.7

    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r ./app/requirements/dev.txt
        continue-on-error: true

#      - name: Run Alembic migrations
#        run: alembic upgrade head
#        env:
#          POSTGRES_HOST: postgres
#          POSTGRES_PORT: 5432
#          POSTGRES_DB: test_db
#          POSTGRES_USER: user
#          POSTGRES_PASSWORD: password
#        working-directory: ./app

      - name: Run tests
        run: pytest -c pytest.test.ini
        working-directory: ./app
