name: Run tests with PostgreSQL service
on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: python:3.10.7

    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r ./app/requirements/dev.txt
        continue-on-error: true

      - name: Run Alembic migrations
        run: alembic upgrade head
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          TEST_DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}
          REDIS_URL: ${{secrets.REDIS_URL}}
          ENVIRONMENT: ${{secrets.TEST_ENVIRONMENT}}

        working-directory: ./app

      - name: Run tests
        run: pytest -c pytest.test.ini
        working-directory: ./app
